---
host:
  hostname: node
  worker: 1 # worker node count
  cpu: 2
  memory: 4096
  deployment: cluster # control plane deployment: cluster (3 nodes) or single (1 node)
support_user: support
ip:
  network: '192.168.3'
  start: 40
  domain: 'test.local'
  vip_hostname: cluster
  vip: 35
bridge: "enp6s0f0"
install_addons: false
software:
  box: bento/ubuntu-24.04
